# Makefile to generate vtuber.dict

DICTS_DIR = dicts
DIST = dist/vtuber.dict
SED = sed
T =  # alias of ADD_TARGET
ADD_TARGET = $(T)
removeHeader = grep -v '^;;;.*'
createDict = cat $(DICTS_DIR)/$@.vtuber.dict | $(removeHeader) >> $(DIST)

all: avatar20project kojin kamitsubaki hololive

# Check if make target is available for all dictionaries
test:
	cd dicts; for f in *.vtuber.dict; do \
		name=$${f/.vtuber.dict/}; \
		grep "^$$name: header" ../Makefile >/dev/null || { \
			echo "Make target for $$name is missing. Please Add." >&2 \
			exit 1; \
		}; \
		grep "^all: .*$$name.*" ../Makefile >/dev/null || { \
			echo "Make target for $$name is not in 'all' target. Please Add." >&2 \
			exit 2; \
		}; \
	done

list:
	grep "^all: .*$$" Makefile | tail -c +6

# Add new make target to Makefile
add:
	[ -z "$(ADD_TARGET)" ] && { echo "no target specified" >&2; exit 1; }; \
	printf '\n$(ADD_TARGET): header\n	$$(createDict)' >> Makefile

header:
	echo ";;; This file is generated by Make on $$(date --rfc-email)" > $(DIST)
	cat src/header.txt >> $(DIST)

# Targets for each affiliation
# Specify targets that you want to include
# Also, please add new target if you add new affiliation file

a2p: avatar20project

avatar20project: header
	$(createDict)

kojin: header
	$(createDict)

hololive: header
	$(createDict)

kamitsubaki: header
	$(createDict)
