# Makefile to generate vtuber.dict

DICTS_DIR = "dicts"
DIST = "dist/vtuber.dict"
SED = "sed"
removeHeader = grep -v '^;;;.*'
createDict = cat $(DICTS_DIR)/$@.vtuber.dict | $(removeHeader) >> $(DIST)

all: avatar20project kojin kamitsubaki hololive


header:
	echo ";;; This file is generated by Make on $$(date --rfc-email)" > $(DIST)
	cat src/header.txt >> $(DIST)

# Targets for each affiliation
# Specify targets that you want to include
# Also, please add new target if you add new affiliation file

a2p: avatar20project

avatar20project: header
	$(createDict)

kojin: header
	$(createDict)

hololive: header
	$(createDict)

kamitsubaki: header
	$(createDict)
